# Generated by Django 5.0.1 on 2024-02-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AddField(
            model_name='usuario',
            name='idUsuario',
            field=models.BigAutoField(default='', primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
