from .produtor_views import ProdutorViewSet
from .propriedade_views import PropriedadeViewSet
from .vinculo_views import VinculoViewSet
from .analise_automatica_views import AnaliseAutomaticaViewSet
from .historico_busca_views import HistoricoBuscaList