from .protudor_serializer import ProdutorSerializer
from .propriedade_serializer import PropriedadeSerializer
from .vinculo_serializer import VinculoSerializer
from .analise_automatica_serializer import AnaliseAutomaticaSerializer
