# Generated by Django 5.0.1 on 2024-02-02 16:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseAutomatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produtorNome', models.CharField(blank=True, max_length=100, null=True)),
                ('produtorCpf', models.CharField(blank=True, max_length=15, null=True)),
                ('propriedadeNome', models.CharField(blank=True, max_length=100, null=True)),
                ('car', models.CharField(blank=True, max_length=100, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, max_length=100, null=True)),
                ('estadoMonitoramento', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'analiseAutomatica',
            },
        ),
        migrations.CreateModel(
            name='HistoricoBusca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo_busca', models.CharField(max_length=255)),
                ('data_hora_busca', models.DateTimeField(default=django.utils.timezone.now)),
                ('resultado_busca', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Produtor',
            fields=[
                ('idProdutor', models.BigAutoField(primary_key=True, serialize=False)),
                ('registroIndividual', models.CharField(blank=True, max_length=100, null=True)),
                ('nomeProdutor', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'produtores',
            },
        ),
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('idPropriedade', models.BigAutoField(primary_key=True, serialize=False)),
                ('nomePropriedade', models.CharField(blank=True, max_length=100, null=True)),
                ('numeroCar', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, max_length=100, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
                ('liberado', models.IntegerField()),
            ],
            options={
                'db_table': 'propriedades',
            },
        ),
        migrations.CreateModel(
            name='Vinculo',
            fields=[
                ('idVinculo', models.BigAutoField(primary_key=True, serialize=False)),
                ('idProdutor', models.ForeignKey(db_column='idProdutor', on_delete=django.db.models.deletion.CASCADE, to='monitoramento_ambiental.produtor')),
                ('idPropriedade', models.ForeignKey(db_column='idPropriedade', on_delete=django.db.models.deletion.CASCADE, to='monitoramento_ambiental.propriedade')),
            ],
            options={
                'db_table': 'vinculos',
            },
        ),
    ]
