# Generated by Django 5.0.1 on 2024-02-01 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseAutomatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produtorNome', models.CharField(blank=True, max_length=100, null=True)),
                ('produtorCpf', models.CharField(blank=True, max_length=15, null=True)),
                ('propriedadeNome', models.CharField(blank=True, max_length=100, null=True)),
                ('car', models.CharField(blank=True, max_length=100, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, max_length=100, null=True)),
                ('estadoMonitoramento', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registroIndividual', models.CharField(blank=True, max_length=100, null=True)),
                ('nomeProdutor', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomePropriedade', models.CharField(blank=True, max_length=100, null=True)),
                ('numeroCar', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, max_length=100, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
                ('liberado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProdutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoramento_ambiental.produtor')),
                ('idPropriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoramento_ambiental.propriedade')),
            ],
        ),
    ]
