# Generated by Django 5.0.1 on 2024-02-01 17:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento_ambiental', '0002_alter_analiseautomatica_table_alter_produtor_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoBusca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo_busca', models.CharField(max_length=255)),
                ('data_hora_busca', models.DateTimeField(default=django.utils.timezone.now)),
                ('resultado_busca', models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='produtor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='propriedade',
            name='id',
        ),
        migrations.RemoveField(
            model_name='vinculo',
            name='id',
        ),
        migrations.AddField(
            model_name='produtor',
            name='idProdutor',
            field=models.BigAutoField(default='', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propriedade',
            name='idPropriedade',
            field=models.BigAutoField(default='', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vinculo',
            name='idVinculo',
            field=models.BigAutoField(default='', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vinculo',
            name='idProdutor',
            field=models.ForeignKey(db_column='idProdutor', on_delete=django.db.models.deletion.CASCADE, to='monitoramento_ambiental.produtor'),
        ),
        migrations.AlterField(
            model_name='vinculo',
            name='idPropriedade',
            field=models.ForeignKey(db_column='idPropriedade', on_delete=django.db.models.deletion.CASCADE, to='monitoramento_ambiental.propriedade'),
        ),
    ]
